//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN_Control
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyPhongGameEntities1 : DbContext
    {
        public QuanLyPhongGameEntities1()
            : base("name=QuanLyPhongGameEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KhoHang> KhoHangs { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
