//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN_Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string TenTK { get; set; }
        public Nullable<bool> Loai { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<System.DateTime> Ngaygio { get; set; }
        public string ChiTiet { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
