//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN_Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string TenTk { get; set; }
        public string MatKhau { get; set; }
        public string ChuTK { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> SoDuTaiKhoan { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
